[project]
name = "zero-to-million"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "locust>=2.37.14",
    "uvicorn>=0.35.0",
]
